-- 檢查資料庫中表的結構
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, COLUMN_KEY, COLUMN_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'kuji'
AND TABLE_NAME IN ('store', 'user')
ORDER BY TABLE_NAME, ORDINAL_POSITION;
